// ignore_for_file: constant_identifier_names

const String HOME_ROUTE="/";
const String CUSTOMER_ROUTE="/customer_home";
const String SPLASH_SCREEN='/spolash_screen';
const String GET_STARTED='/get_started';
const String SIGN_UP='/signup';
const String USER_REGISTER='/userregister';
const String TERMS_AND_CONDITION='/terms_and_condition';
const String CREATE_JORNEY='/create_journey';
const String CUSTOMER_TRIP_REQUEST='/customer_trip_request';
const String VIEW_DRIVER_JOURNEY_DETAILS='/driver_journey_details';
const String VIEW_TRIP_REQUEST_DETAILS='/trip_request_details';
const String CUSTOMER_POSTED_JOURNEYS='/customer_posted_journeys';
const String CUSTOMER_POSTED_JOURNEY_DETAILS='/customer_posted_journey_details';
const String CUSTOMER_TRIP_REQUEST_DETAILS='/customer_trip_request_details';
const String SEARCH_PLACES='/search_places';
const String CUSTOMER_CREATE_TRIP_REQUEST='/customer_create_trip_request';
const String VIEW_JOINED_PASSENGERS='/view_joined_passengers';
const String USER_PROFILE='/user_profile';
const String EDIT_USER_PROFILE='/edit_edit_profile';
const String NOTIFICATION_PAGE='/notifiaction_page';
const String NOTIFICATIONS_LIST_PAGE='/notification_list_page';