// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
 
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPMBxEKWfCvQ6w4kGQTEErGPBkV2I8p30',
    appId: '1:224702379481:android:17f2a4dfc03b63e7ff95c8',
    messagingSenderId: '224702379481',
    projectId: 'easilygo-e5baa',
    storageBucket: 'easilygo-e5baa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtLTByBABE2gdcHQ7PJrkUZOM5_2Uf9g',
    appId: '1:224702379481:ios:48c3a37bc32b4558ff95c8',
    messagingSenderId: '224702379481',
    projectId: 'easilygo-e5baa',
    storageBucket: 'easilygo-e5baa.appspot.com',
    iosBundleId: 'com.example.easylygoApp',
  );


}
